export const Tower_Data = [
  { title: "Castle", bg: "bg-red-600" },
  { title: "Tower", bg: "bg-orange-500" },
  { title: "Chamber", bg: "bg-amber-400" },
  { title: "Room", bg: "bg-emerald-500" },
  { title: "Hall", bg: "bg-emerald-600" },
  { title: "Corridor", bg: "bg-blue-500" },
  { title: "Gallery", bg: "bg-indigo-500" },
  { title: "Nook", bg: "bg-purple-600" },
  { title: "Oil", bg: "bg-red-300" },
  { title: "Deer", bg: "bg-amber-300" },
  { title: "Dungeon", bg: "bg-slate-700" },
  { title: "Balcony", bg: "bg-red-400" },
  { title: "Basement", bg: "bg-amber-600" },
  { title: "Attic", bg: "bg-yellow-400" },
  { title: "Library", bg: "bg-lime-500" },
  { title: "Vault", bg: "bg-green-600" },
  { title: "Sanctuary", bg: "bg-emerald-700" },
  { title: "Garden", bg: "bg-teal-500" },
  { title: "Courtyard", bg: "bg-cyan-500" },
  { title: "Armory", bg: "bg-sky-500" },
  { title: "Crypt", bg: "bg-blue-600" },
  { title: "Laboratory", bg: "bg-blue-400" },
  { title: "Observatory", bg: "bg-indigo-700" },
  { title: "Terrace", bg: "bg-violet-600" },
  { title: "Passage", bg: "bg-purple-400" },
  { title: "Keep", bg: "bg-fuchsia-500" },
  { title: "Bridge", bg: "bg-pink-500" },
  { title: "Gatehouse", bg: "bg-rose-500" },
  { title: "Throne Room", bg: "bg-rose-700" },
  { title: "Spire", bg: "bg-zinc-700" },
];
